loginTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
]

tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

tasks/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

tasks/forms.py
from django import forms


class TaskCreationForm(forms.Form):
    title = forms.CharField(label='タイトル', max_length=255)
    content = forms.CharField(label='内容', widget=forms.Textarea())

tasks/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Task
from .forms import TaskCreationForm


def index(request):
    tasks = Task.objects.all()
    params = {
        'tasks': tasks,
    }
    return render(request, 'tasks/index.html', params)


def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        task = Task(title=title, content=content)
        task.save()
        return redirect('tasks:index')
    else:
        params = {
            'form': TaskCreationForm(),
        }
        return render(request, 'tasks/create.html', params)


def detail(request, task_id):
    task = Task.objects.get(id=task_id)
    params = {
        'task': task,
    }
    return render(request, 'tasks/detail.html', params)


def edit(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.title = request.POST['title']
        task.content = request.POST['content']
        task.save()
        return redirect('tasks:detail', task_id)
    else:
        form = TaskCreationForm(initial={
            'title': task.title,
            'content': task.content,
        })
        params = {
            'task': task,
            'form': form,
        }
        return render(request, 'tasks/edit.html', params)


def delete(request, task_id):
    task = Task.objects.get(id=task_id)
    if (request.method == 'POST'):
        task.delete()
        return redirect('tasks:index')
    else:
        params = {
            'task': task,
        }
        return render(request, 'tasks/delete.html', params)

tasks/templates/tasks/create.html
{% extends "base.html" %}

{% block main %}
<h1>Task registration page</h1>
<form action="{% url 'tasks:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="register">
</form>

<br>

<a href="{% url 'tasks:index' %}">return</a>
{% endblock %}

tasks/templates/tasks/delete.html
{% extends "base.html" %}

{% block main %}
<h1>Task deletion page</h1>
<p>
  <strong>title:</strong>
  {{task.title}}
</p>

<p>
  <strong>Content:</strong>
  {{task.content}}
</p>
<form action="{% url 'tasks:delete' task.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="delete">
</form>

<br>

<a href="{% url 'tasks:index' %}">return</a>
{% endblock %}

tasks/templates/tasks/detail.html
{% extends "base.html" %}

{% block main %}
<h1>Task details page</h1>
<p>
  <strong>title:</strong>
  {{task.title}}
</p>

<p>
  <strong>Content:</strong>
  {{task.content}}
</p>
<a href="{% url 'tasks:index' %}">return</a> |
<a href="{% url 'tasks:edit' task.id %}">edit</a>
{% endblock %}

tasks/templates/tasks/edit.html
{% extends "base.html" %}

{% block main %}
<h1>Task edit page</h1>
<form action="{% url 'tasks:edit' task.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

<br>

<a href="{% url 'tasks:detail' task.id %}">detail</a> |
<a href="{% url 'tasks:index' %}">return</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block main %}
<h1>Task list page</h1>
<table>
  <tr>
    <th>title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  {% for task in tasks %}
  <tr>
    <td>{{task.title}}</td>
    <td>{{task.content}}</td>
    <td><a href="{% url 'tasks:detail' task.id %}">detail</a></td>
    <td><a href="{% url 'tasks:edit' task.id %}">edit</a></td>
    <td><a href="{% url 'tasks:delete' task.id %}">delete</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'tasks:create' %}">create</a>

{% endblock %}