loginTask/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('accounts/', include('accounts.urls')),
]

tasks/urls.py
from django.urls import path
from . import views
app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:task_id>', views.detail, name='detail'),
    path('edit/<int:task_id>', views.edit, name='edit'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

templates/base.html
{% load static %}

<html>

  <head>
    <meta charset="utf-8">
    <title>Task</title>
    <link rel="stylesheet" href="{% static 'tasks/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/css/style.css' %}">
  </head>

  <body>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'tasks:index' %}">Tasks list</a></li>
        <li>
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <li><a><button type="submit">Log out</button></a></li>
          </form>
        </li>
        <li><a href="{% url 'user_detail' user.pk %}">Member Information</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'signup' %}">Register user</a></li>
        {% endif %}
      </ul>
    </nav>
    <main>
      <div>
        {% block main %}
        {% endblock %}
      </div>
    </main>
  </body>

</html>